####################################################################
#  Setup Ubuntu UFW firewall
####################################################################
- ufw:
    rule: allow
    name: OpenSSH
- ufw:
    rule: allow
    port: 53
- ufw:
    state: enabled
    policy: allow
